null check to avoid launch crash
immediately hitting the feed tab after launch will produce the following crash, so this resolves it by a null check:

```
java.lang.NullPointerException: Attempt to read from field 'awais.instagrabber.customviews.PostsRecyclerView awais.instagrabber.databinding.FragmentFeedBinding.feedRecyclerView' on a null object reference
	at awais.instagrabber.fragments.main.FeedFragment.scrollToTop(FeedFragment.java:461)
	at awais.instagrabber.utils.NavigationExtensions.lambda$setupItemReselected$2(NavigationExtensions.java:190)
	at awais.instagrabber.utils.-$$Lambda$NavigationExtensions$C3II1R-NOFB80ERAxio06uf3Qto.onNavigationItemReselected(Unknown Source:4)
...
```